import {chromium} from './qa/node_modules/playwright/index.mjs';import assert from 'node:assert/strict';import {writeFile} from 'node:fs/promises';
const url=process.env.BLOCK2SCRIPT_TEST_URL||'http://127.0.0.1:5175/block2script/';
const browser=await chromium.launch({executablePath:process.env.BLOCK2SCRIPT_BROWSER||(process.platform==='win32'?'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe':undefined),headless:true});const context=await browser.newContext({viewport:{width:1500,height:1000}}),errors=[],failedAssets=[];
await context.addInitScript(()=>{window.requestedDevices=0;if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=()=>{window.requestedDevices++;return Promise.reject(Error('Test media guard'));};if(navigator.bluetooth)navigator.bluetooth.requestDevice=()=>{window.requestedDevices++;return Promise.reject(Error('Test bluetooth guard'));};});
const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.url().startsWith(new URL(url).origin)&&r.status()>=400)failedAssets.push({url:r.url(),status:r.status()});});page.on('requestfailed',r=>{if(r.url().startsWith(new URL(url).origin))failedAssets.push({url:r.url(),error:r.failure()?.errorText});});
try{
 const response=await page.goto(url);assert.equal(response.status(),200);await page.waitForFunction(()=>document.querySelector('#scratch-frame')?.contentWindow?.scratchNative?.vm?.editingTarget,{timeout:120000});await page.waitForFunction(()=>document.querySelector('#target').textContent.includes('Block2Bot'));
 const initial=await page.evaluate(()=>{const w=document.querySelector('#scratch-frame').contentWindow;return {iframe:document.querySelector('#scratch-frame').src,devices:w.requestedDevices,supported:Object.keys(w.scratchNative.stretch.supported),camera:!!w.scratchNative.getController().ScratchBlocks.Blocks.cameraselector_selectCamera};});assert.ok(initial.iframe.includes('/block2script/stretch3-dist/'));assert.equal(initial.devices,0);assert.equal(initial.supported.includes('cameraselector'),false);assert.equal(initial.camera,false);
 await page.locator('#stretch').click();assert.equal(await page.locator('#stretch-choices button').count(),5);await page.locator('#extension-information summary').click();assert.equal(await page.locator('#extension-information-list section').count(),9);await page.locator('#close-stretch').click();
 await page.locator('#demo').click();assert.equal(await page.locator('#apply').isEnabled(),true);await page.locator('#apply').click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('反映しました'));await page.locator('#verify').click();assert.match(await page.locator('#status').textContent(),/差はありません/);await page.locator('#undo').click();
 await page.locator('#help').click();assert.ok(await page.locator('#help-dialog a').filter({hasText:'対応ソース'}).count());await page.locator('#close-help').click();await page.screenshot({path:'stretch3-base/qa/pages-smoke.png'});
 assert.deepEqual(errors,[]);assert.deepEqual(failedAssets,[]);await writeFile('stretch3-base/qa/pages-smoke-result.json',JSON.stringify({pass:true,url,checks:['HTML/assets','subpath iframe/dynamic assets','Block2Bot','five licensed source extensions','Camera Selector excluded','no startup device requests','validate/apply/roundtrip/Undo','corresponding source link'],errors,failedAssets},null,2));console.log('Pages subpath smoke checks passed.');
}finally{await browser.close();}
